# Generated by Django 4.1 on 2022-10-13 02:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0004_task_delete_todolist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='ToDoList',
        ),
    ]
