# Generated by Django 4.1 on 2022-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_mywatchlist_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='title',
            field=models.TextField(),
        ),
    ]
